#!/bin/bash

if [ -z "$1" ];then
    jockjsPath=/home/www/release/node/fp00
else
    tpl=$1
fi

if [ ! -f $jockjsPath ];then
    mkdir -p $jockjsPath
fi


cd $jockjsPath
git clone git@git.corp.anjuke.com:aifang/jockjs
git clone git@git.corp.anjuke.com:aifang/jockcss
git clone git@git.corp.anjuke.com:site/jockjs-touch
git clone git@git.corp.anjuke.com:site/jockjs-components


