#!/bin/bash
commond=$1
version=$2
if [ -z "$3" ];then
    tpl="fp00"
else
    tpl=$3
fi
forever=/usr/local/bin/forever
jockjsPath=/home/www/release/node
jockjsLogPath=/data1/logs/node
jockjsConfPath=/home/www/config/node

if [ ! -f "$forever" ];then
  forever=/home/www/bin/forever
else
  forever=forever
fi

function forever_action(){
  if [ "$1" = "start" -o "$1" = "restart" -o "$1" = "reload" ];then
    forever_stop $2
    forever_start $2
  fi
  if [ "$1" = "stop" ];then
    forever_stop $2
  fi
}

function forever_start(){
  if [ -z "$1" ];then
    fpPath=fp00
  else
    fpPath=$1
  fi
  $forever start -a -l $jockjsLogPath/js.log $jockjsPath/$fpPath/jockjs/service.js $jockjsConfPath/$fpPath.js
  $forever start -a -l $jockjsLogPath/css.log $jockjsPath/$fpPath/jockcss/service.js $jockjsConfPath/$fpPath.css
}

function forever_stop(){
  if [ -z "$1" ];then
    fpPath=fp00
  else
    fpPath=$1
  fi
  $forever stop $jockjsPath/$fpPath/jockjs/service.js
  $forever stop $jockjsPath/$fpPath/jockcss/service.js
}

function forever_list(){
  $forever list
}

function git_pull(){
  cd $jockjsPath/$1
  ls | while read path; do 
    cd $jockjsPath/$1/$path;
    echo "current path : $jockjsPath/$1/$path";
    git branch 
    git pull --rebase; 
  done;  
}

function git_co_master(){
  cd $jockjsPath/$1
  ls | while read path; do 
    cd $jockjsPath/$1/$path;
    echo "current path : $jockjsPath/$1/$path";
    git co master
    git pull --rebase; 
  done;  
}

function git_install(){
  if [ -z "$1" ];then
    jockjsPath=/home/www/release/node/$2
  fi

  if [ ! -f $jockjsPath ];then
    mkdir -p $jockjsPath
  fi
  cd $jockjsPath
  git clone git@git.corp.anjuke.com:aifang/jockjs
  git clone git@git.corp.anjuke.com:aifang/jockcss
  git clone git@git.corp.anjuke.com:site/jockjs-touch
  git clone git@git.corp.anjuke.com:site/jockjs-components  
 
}

function node_install(){
   
}


if [[ "$commond" = "install" && ! -z "$version" ]];then
   git_install "$commond" "$version"
   exit 0
fi



if [[ "$commond" = "domain" && ! -z "$version" ]];then
    cd $jockjsConfPath
    sed -i "" s#jockjs.fp00.dev.aifcdn.com#$version#g fp00.js
    sed -i "" s#jockjs.fp00.dev.aifcdn.com#$version#g fp00.css
    echo ""
    echo "jockjs domain change to : $version "
    exit 0
fi


if [[ "$commond" = "create" && ! -z "$version" ]];then
    v=${version:2:2}
    cd $jockjsPath
    rm -rf "$version"
    cp -r "$tpl" "$version"
    #git_co_master "$version"
    cd $jockjsConfPath
    cp "$tpl".js "$version".js
    cp "$tpl".css "$version".css
    sed -i s#$tpl#$version#g "$version".js
    sed -i s#$tpl#$version#g "$version".css
    sed -i s#52100#521$v#g "$version".js
    sed -i s#52200#522$v#g "$version".css
    echo ""
    echo "$version created. "
    exit 0
fi


if [ "$commond" = "reload" -o "$commond" = "restart" -o "$commond" = "start" -o "$commond" = "stop" -o "$commond" = "list" -o "$commond" = "pull" ];then
    if [ "$commond" = "list" ];then
        forever_$commond
        exit
    fi 
   
    if [ "$commond" = "pull" ];then
        if [ ! -z "$version" ];then
            git_pull "$version"
        else
            echo "use jockjs pull fpxx"
       fi
    else
        forever_action "$commond" "$version"
    fi
else
    echo "use jockjs restart|reload|stop|start|list|pull"
fi
